### PR TITLE
Frontend: add improvements

### PR DESCRIPTION
**Pull request by arsalanc-v2**
Adds the following:
* minor UI changes (colors, fonts)
* removed unused google fonts to reduce build size
* added collapsible support for arrays
* shows number of elements for collapsed objects and arrays

blotvis

### CODE REVIEW

**Comment by halcon-blanco** [comment]
The collapse triangle is too close to the data

**Comment by halcon-blanco** [comment]
Font size is a little too big. Would take up too much space very quickly as data gets bigger

**Comment by halcon-blanco** [comment]
Would it be better to expand arrays vertically instead. If the array contains bigger data, expanding horizontally would be unsightly. Also, we could add indexing of the elements to the array's left

**Comment by arsalanc-v2** [comment]
> The collapse triangle is too close to the data

Yep, fixed it (#4 )

**Pull request merged**
